spring:
  application:
    name: news-system-management
  profiles:
    active: prod
  config:
    import: optional:configserver:http://${CONFIG_HOST:localhost}:8888/
  cloud:
    config:
      enabled: true
      failFast: true